wfra/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

wfra/characters/urls.py
from django.urls import path
from . import views

app_name = 'characters'

urlpatterns = [
    path('', views.ListCharacters.as_view(), name="all"),
    path("create/", views.CreateCharacter.as_view(), name="create"),
    path("<int:pk>/", views.DetailViewCharacter.as_view(), name="detail"),
    path("update/<int:pk>/", views.UpdateViewCharacter.as_view(), name="update"),
    path("delete/<int:pk>/", views.DeleteViewCharacter.as_view(), name="delete"),
]

wfra/wfra/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('characters/', include('characters.urls', namespace='characters')),
    path('equipment/', include('equipment.urls', namespace='equipment')),
    path('about/', views.AboutPage.as_view(), name="about"),
    path("api/career-options/", views.career_options_api, name="career-options-api"),
    path("api/career-paths/", views.career_paths_api, name="career-paths-api"),
]

wfra/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<br>
<div class="jumbotron">
    <h1>About the Application</h1>
    <h3>This application allows users to manage their characters from the Warhammer Fantasy Roleplay game.
    Registration is required to access all website functionalities. Character creation is done by
    completing a form.</h3>

    <h3>Please note that all information in the form is required. If some fields are not relevant,
    an acceptable answer should be 'None', '-' or '0' in the case of numerical values. If a character does not have any
    advanced skills, these fields should be filled with placeholders.</h3>

    <h3>Character details can be accessed from the main list of user characters. In the detail view, users have
    the option to update or delete a character.</h3>

    <h3><b>Important:</b> Deleting a character is permanent!</h3>

    <h3>Full software documentation of this application can be viewed on this
        <a href="https://patrickschroeder98.github.io/software_documentation/warhammer_roleplay_app_docs/index.html">
            website
        </a>.
    </h3>
</div>

<div class="jumbotron">
    <h1>About the Author</h1>
    <h3>I'm a passionate Warhammer Fantasy fan and a software engineer specializing in Python programming.</h3>
    <h3>See my other projects in my <a href="https://patrickschroeder98.github.io/portfolio/index.html">Portfolio</a>.</h3>
</div>

<div class="jumbotron">
    <section id="contact" class="contact-section">
        <h2 data-i18n="contact-header">Contact Me</h2>
        <div class="contact-info">
            <a href="mailto:patrickschroeder479@gmail.com">patrickschroeder479@gmail.com</a>
            <span></span>

            <a href="https://www.linkedin.com/in/patrick-schröder-6b2007263/" target="_blank">
                <img src="{% static 'wfra/img/linkedin.png' %}" alt="LinkedIn">
            </a>
            <span></span>
            <a href="https://github.com/PatrickSchroeder98/" target="_blank">
                <img src="{% static 'wfra/img/github-mark-white.png' %}" alt="GitHub">
            </a>
        </div>
    </section>
</div>

{% endblock %}

wfra/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel ="icon" href="{% static 'wfra/ico/wfra.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'wfra/css/styles.css'%}">

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>

    <!-- Toggle button for mobile -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>

        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'characters:all' %}">Characters</a>
          </li>
          <li class="nav-item">
            <form action="{% url 'logout' %}" method="post" class="d-inline">
              {% csrf_token %}
              <input class="btn btn-link nav-link" type="submit" value="Logout">
            </form>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<div class="d-flex flex-column min-vh-100">
  <div class = "container flex-grow-1">
    {% block content %}
    {% endblock %}
  </div>
    <footer class="py-3 text-light">
    <div class="container-fluid text-center">
        <p class="mb-0 text-wrap">&copy; 2025, Patrick Schröder, WFRA. All rights reserved.
          <br class="d-block d-sm-none">
        All logos are trademarks of their respective owners and are used here for informational purposes only.</p>
    </div>
    </footer>
  </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>

wfra/templates/index.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="jumbotron">
    <h1>Warhammer Fantasy Roleplay Application</h1>
</div>

<div class="jumbotron">
    <h2>This application allows you to create and manage characters from Warhammer Fantasy Roleplay game.</h2>
</div>

<div class="jumbotron">
    <h2>Stay tuned for more updates soon!</h2>
</div>

{% endblock %}